_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/mask_rcnn/mask_rcnn_R_101_FPN_1shot/model_final.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
  ROI_HEADS:
    NUM_CLASSES: 80
    FREEZE_FEAT: True
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
    FREEZE_PRED: False
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: True
    FREEZE_PRED: False
    FREEZE_FEAT: True
DATASETS:
  TRAIN: ('pascal_voc_2012_val',)
  TEST: ('pascal_voc_2012_val',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (14400,)
  CHECKPOINT_PERIOD: 1000
  MAX_ITER: 26000
  WARMUP_ITERS: 10
OUTPUT_DIR: "checkpoints/coco/mask_rcnn/mask_rcnn_R_101_FPN_1shot"
