_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "MetaRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "MetaRes5ROIHeads"
    NUM_CLASSES: 60
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: False
  ROI_MASK_HEAD:
    CLS_AGNOSTIC_MASK: False
DATASETS:
  TRAIN: ('coco_train_base',)
  TEST: ('coco_val_base',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 2000
OUTPUT_DIR: "checkpoints/coco/meta_rcnn/meta_rcnn_R_101_FPN_base"